apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: scaleup-deployment
spec:
  selector:
    matchLabels:
      app: scaleup
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: scaleup
    spec:
      containers:
      - name: scaleup
        image: rabbitmq
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "1"
      tolerations:
      - key: "key"
        value: "value1"
        operator: "Equal"
        effect: "NoSchedule" 
